### ISSUE TITLE
Q&A policy

### ISSUE THREAD

**Issue by sirasris** [sirasris/AI_Academy_2020#1]
Please create new issue here to ask questions rather than emailing our staffs. That way everyone will be able to get the same information.

- We will answer questions that clarify the intent of the problems. 
- We will NOT answer questions about techniques or approaches. For this exam, you are given complete freedom to explore and approach the problems from any angle.
- We will NOT answer questions about the meaning of each input feature. For this exam, you are not supposed to utilize any domain knowledge about the problems.

Enjoy the exam!

**Comment by RawinChanpitak** [comment]
Hi,

I am working on question 1,2 and I have several questions to ask.

1. Does the patient status tell us that 0 = death and 1 = alive for question '2'

2. If the dataset can be predicted very precisely by a very simple model for question '2' without using ROI information. Should examiners stop using more sophisticate model or continue further ? This raises me quite a concern because the task is complete but the ROI is not used. Does this imply that examiners should spend more time in other sector ? Or, does the exam purpose is to examine the knowledge of each individual or only how examiner handle the problem or both ?

3. In question '1', the information of whether ELIspot is positive or negative is unknown. Examiners know only the quantity of ELIspot. My question is the number '0' in ELIspot_result indicate negative outcome and ELIspot_result > 0 indicate positive outcome? This conclusion that I draw is based on the picture that appear along with the zipfile.

best regards
