### ISSUE TITLE
Question about problems 1 and 2

### ISSUE THREAD

**Issue by RawinChanpitak** [sirasris/AI_Academy_2020#2]
Hi,

I am working on question 1,2 and I have several questions to ask.

Does the patient status tell us that 0 = death and 1 = alive for question '2'

If the dataset can be predicted very precisely by a very simple model for question '2' without using ROI information. Should examiners stop using more sophisticate model or continue further ? This raises me quite a concern because the task is complete but the ROI is not used. Does this imply that examiners should spend more time in other sector ? Or, does the exam purpose is to examine the knowledge of each individual or only how examiner handle the problem or both ?

In question '1', the information of whether ELIspot is positive or negative is unknown. Examiners know only the quantity of ELIspot. My question is the number '0' in ELIspot_result indicate negative outcome and ELIspot_result > 0 indicate positive outcome? This conclusion that I draw is based on the picture that appear along with the zipfile.

best regards

**Comment by sirasris** [comment]
> Does the patient status tell us that 0 = death and 1 = alive for question '2'

We are sorry for the problem. Due to technical issue, the descriptions of features were missing from the data files. We have provided these information in the front page of this exam repo. To answer your question here, Alive = 0, Dead = 1, Unknown = -1.

> If the dataset can be predicted very precisely by a very simple model for question '2' without using ROI information. Should examiners stop using more sophisticate model or continue further ? This raises me quite a concern because the task is complete but the ROI is not used. Does this imply that examiners should spend more time in other sector ? Or, does the exam purpose is to examine the knowledge of each individual or only how examiner handle the problem or both ?

This exam is designed to test the judgement and reasoning ability of the examinee as well as technical skills. If you have a reason or evidence to suggest that one approach is better than another, just clarify your decision and show evidence supporting your decision in your submission.

> In question '1', the information of whether ELIspot is positive or negative is unknown. Examiners know only the quantity of ELIspot. My question is the number '0' in ELIspot_result indicate negative outcome and ELIspot_result > 0 indicate positive outcome? This conclusion that I draw is based on the picture that appear along with the zipfile.

Again, we are sorry for the technical issue. The details of features for Problem 1 have been added to the front page of this exam repo. To answer your question here, the ground truth label that the model should predict is contained in column **Drug_Rechallenge_Result**. ELISpot test result should be treated as an input to your prediction model.

**Comment by sirasris** [comment]
Just to clarify, since the descriptions of some variables were added after you began the exam, **Time to Event** in Problem 2 is part of the information used to label the patient status at 3-year mark and should not be considered as input to your model. The 6 patient characteristics that may be used are: **gender**, **age**, and **clinical A-D**

This clarification has been added to the front page of this exam repository.
